### ISSUE TITLE
Can there be a Discord?

### ISSUE THREAD

**Issue by MarshMeadow** [6ixline/Animasi#11]
I would like to chat more about this in like a server or a private chat, I might be able to help maybe.

**Comment by 6ixline** [comment]
![Screenshot_2022-11-15-23-49-05-02_572064f74bd5f9fa804b05334aa4f912](https://user-images.githubusercontent.com/33677623/201996238-3b7c15c9-cc42-48ea-8ba4-8a20adc0b56a.jpg)

**Comment by 6ixline** [comment]
Drop a msg here

**Comment by MarshMeadow** [comment]
Sent...

**Comment by MarshMeadow** [comment]
I am neko404.
